@Library("jenlib") _

Map<String, Object> pipelineOptions = [
		projects: ["s2pp"],
		moduleOptions: [modules: ["ppu-toolchain"]],
		container: [app: "dls"],
		notificationChannel: "#dls-software"
]

if (!isTriggeredByGerrit()) {
	pipelineOptions << [
			testSlurmResource: getHxTestResource(3),
			preTestHook: { configureHxCubeBitfile() },
			testOptions: "--test-execall -j1",
	]
}

wafDefaultPipeline(pipelineOptions)
